router bgp 300
  bgp router-id 10.100.3.1
  no bgp ebgp-requires-policy
  no bgp enforce-first-as

  neighbor 10.0.0.254 remote-as 1337
  neighbor 10.0.0.254 timers 10 30
  neighbor 10.0.2.2 remote-as 400
  neighbor 10.0.2.2 timers 10 30

  address-family ipv4 unicast
    network 10.3.0.0/24
    network 10.0.0.0/24
  exit-address-family
