route-map PREFER_AS3 permit 10
  set local-preference 200

route-map PREFER_AS3 permit 20

router bgp 400
  bgp router-id 10.100.4.1
  no bgp ebgp-requires-policy

  neighbor 10.0.1.1 remote-as 200
  neighbor 10.0.1.1 timers 3 9
  neighbor 10.0.2.1 remote-as 300
  neighbor 10.0.2.1 timers 3 9

  address-family ipv4 unicast
    neighbor 10.0.2.1 route-map PREFER_AS3 in
    network 10.4.0.0/24
  exit-address-family
