router bgp 400
  bgp router-id 10.100.4.1
  no bgp ebgp-requires-policy

  neighbor 10.0.1.1 remote-as 200
  neighbor 10.0.1.1 timers 10 30
  neighbor 10.0.2.1 remote-as 300
  neighbor 10.0.2.1 timers 10 30

  address-family ipv4 unicast
    network 10.4.0.0/24
    network 10.0.1.0/24
    network 10.0.2.0/24
  exit-address-family
