router bgp 500
  bgp router-id 100.100.5.1
  no bgp ebgp-requires-policy

  neighbor 16.2.2.1 remote-as 300

  address-family ipv4 unicast
  	network 16.1.5.0/24
    network 16.2.2.0/24
  exit-address-family
