router bgp 600
  bgp router-id 100.100.6.1
  no bgp ebgp-requires-policy

  neighbor 16.2.3.1 remote-as 400

  address-family ipv4 unicast
  	network 16.1.6.0/24
    network 16.2.3.0/24
  exit-address-family
