router id 100.100.254.1;


## BASED on https://blog.kintone.io/entry/bird#:~:text=Protocol%20template,same%20configurations%20from%20template%20tor%20.
## AND https://gist.github.com/macros/3791374
protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import none;
        export all;
    };
}

protocol static {
    ipv4;
}

# Connection to the route server
protocol bgp route_server {
    local 16.2.1.5 as 1401;
    neighbor 16.2.1.254 as 1337;
    ipv4 {
        import all;
        export all;
    };
    hold time 90;
    keepalive time 30;
}

# BGP session with AS7, to exchange routes with the rest of the Internet
protocol bgp as7r1 {
    local 16.2.4.1 as 1401;
    neighbor 16.2.4.2 as 700;
    ipv4 {
        import all;
        export all;
    };
    hold time 90;
    keepalive time 30;
}
