router id 10.100.255.1;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        export none;
    };
}

protocol static {
    ipv4;
}

# Template for BGP route server clients
template bgp rs_client {
    local 10.0.0.254 as 1337;
    rs client;
    ipv4 {
        import all;
        export all;
    };
    hold time 30;
    keepalive time 10;
}

# AS1, AS2, AS3 are directly connected to the SDX
# AS4 is not directly connected, it exchanges routes through AS2 and AS3
protocol bgp as1r1 from rs_client {
    neighbor 10.0.0.1 as 100;
}

protocol bgp as2r1 from rs_client {
    neighbor 10.0.0.2 as 200;
}

protocol bgp as3r1 from rs_client {
    neighbor 10.0.0.3 as 300;
}
