router id 100.100.255.1;

## BASED on https://blog.kintone.io/entry/bird#:~:text=Protocol%20template,same%20configurations%20from%20template%20tor%20.
## AND https://gist.github.com/macros/3791374
protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        export none;
    };
}

protocol static {
    ipv4;
}

# Template for BGP route server clients, to avoid repeating the same configurations for each client
template bgp rs_client {
    local 16.2.1.254 as 1337;
    rs client;
    ipv4 {
        import all;
        export all;
    };
    hold time 90;
    keepalive time 30;
}

# BGP sessions with the route server and the other ASes. AS5/AS6/AS7 are not directly connected to the route server, 
#but they exchange routes with it through AS1/AS2/AS3/AS4, so they are not configured as clients of the route server.
protocol bgp as1r1 from rs_client {
    neighbor 16.2.1.1 as 100;
}

protocol bgp as2r1 from rs_client {
    neighbor 16.2.1.2 as 200;
}

protocol bgp as3r1 from rs_client {
    neighbor 16.2.1.3 as 300;
}

protocol bgp as4r1 from rs_client {
    neighbor 16.2.1.4 as 400;
}

protocol bgp isp1r1 from rs_client {
    neighbor 16.2.1.5 as 1401;
}
