route-map PREFER_AS2 permit 10
  set local-preference 200

route-map PREFER_AS2 permit 20

router bgp 100
  bgp router-id 10.100.1.1
  no bgp ebgp-requires-policy
  no bgp enforce-first-as

  neighbor 10.0.0.2 remote-as 200
  neighbor 10.0.0.2 timers 3 9
  neighbor 10.0.0.3 remote-as 300
  neighbor 10.0.0.3 timers 3 9

  address-family ipv4 unicast
    neighbor 10.0.0.2 route-map PREFER_AS2 in
    network 10.1.0.0/24
  exit-address-family
